### ISSUE TITLE
Labelling errors in Chapter 4

### ISSUE THREAD

**Issue by prrathi** [OpenRG/OGprimer#4]
Some of the exercises, equations, or diagrams in Chapter 4 seem to be referenced incorrectly, usually being labeled from Chapter 5 instead of 4:
- 'Exercise 5.1' on page 49 should be Exercise 4.1
- 'Definition 5.1' and 'Definition 5.2' on page 55 should be Definition 4.1 and Definition 4.2
- 'Table 5.3' on page 58 should be Table 4.3
- 'Table 5.1' on page 59 should be Table 4.1
- 'Definition 5,2', 'Table 5.1', and 'Table 5.3' on page 60
- 'Equation 6.26' on page 61 should be Equation 4.26
- 'Figure 5.1', 'Figure 5.2', and 'Table 5.2' on page 62
- 'Exercise 5.1' on page 67
- 'Definition 5.1' on page 70
- 'Exercise 5.3' on page 71

**Comment by rickecon** [comment]
These errors were fixed in PR #5. Thanks @prrathi.
